############################################################
# +------------------------------------------------------+ #
# |      OrePlus created by UltraMCPro & jaquadro        | #
# +------------------------------------------------------+ #
############################################################


    #You can found a video about this plugin on http://bit.ly/SubUltra
    #You can also subscribe for updates on the OrePlus project along side funny and amazing videos
 
default:
    verbose-startup: false
    generate:   
    	#Iron Ore
        - block: IRON_ORE
          enabled: true
          size: 8
          rounds: 3
          min-height: 0
          max-height: 64
        #Gold Ore
        - block: GOLD_ORE
          enabled: true
          size: 8
          rounds: 2
          min-height: 0
          max-height: 32
        #Diamond Ore
        - block: DIAMOND_ORE
          enabled: true
          size: 7
          rounds: 1
          min-height: 0
          max-height: 16
        #Emerald Ore
        - block: EMERALD_ORE
          enabled: true
          size: 7
          rounds: 1
          min-height: 0
          max-height: 16
          probability: 0.25
          #Set the biomes where ore can generate differently
          biomes: [EXTREME_HILLS, JUNGLE_HILLS]
          
    #Here you can enable or disable the replacement of the ore generation you have set above  
    clear:
        - block: EMERALD_ORE
          enabled: false
          min-height: 0
          max-height: 32
